src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\File\File;

#[Vich\Uploadable]
#[UniqueEntity(
    'title',
    message: 'Ce titre existe déjà'
)]
#[ORM\Entity(repositoryClass: PropertyRepository::class)]
class Property
{

    const HEAT = [
        0 => 'electric',
        1 => 'gaz'
    ];

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Assert\Length(min:5, max:255)]
    #[ORM\Column(type: 'string', length: 255, unique: 'true')]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[Assert\Range(min: 10, max: 400, notInRangeMessage: 'You must be between {{ min }}cm and {{ max }}cm tall to enter')]
    #[ORM\Column]
    private ?int $surface = null;

    #[ORM\Column]
    private ?int $bedrooms = null;

    #[ORM\Column]
    private ?int $floor = null;

    #[ORM\Column]
    private ?int $price = null;

    #[ORM\Column]
    private ?int $heat = null;

    #[ORM\Column(length: 255)]
    private ?string $city = null;

    #[ORM\Column(length: 255)]
    private ?string $address = null;

    #[Assert\Regex('/^[0-9]{5}$/')]
    #[ORM\Column(length: 255)]
    private ?string $postal_code = null;

    #[ORM\Column]
    private ?bool $sold = false;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?int $rooms = null;

    #[ORM\ManyToMany(targetEntity: Option::class, inversedBy: 'properties')]
    private Collection $options;

    #[Assert\File(mimeTypes: "image/jpeg")]
    #[Vich\UploadableField(mapping: 'property_images', fileNameProperty: 'imageName')]
    private ?File $imageFile = null;

    #[ORM\Column(type: 'string', nullable: true)]
    private ?string $imageName = null;

    #[ORM\Column(type: 'datetime')]
    private ?\DateTimeInterface $updatedAt = null;

    //#[ORM\Column]
    //private ?string $slug = null;

    public function __construct(){
        $this->created_at = new \DateTimeImmutable();
        $this->options = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getFormatedPrice(): string
    {
        return number_format($this->price, 0, '', ' ');
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getHeatType(): string
    {
        return self::HEAT[$this->heat];
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function isSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection<int, Option>
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options->add($option);
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->removeElement($option)) {
            $option->removeProperty($this);
        }

        return $this;
    }

    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $this->imageFile && $this->imageFile instanceof UploadedFile) {
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }
}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Property;
use App\Entity\Option;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichImageType;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('bedrooms')
            ->add('floor')
            ->add('price')
            ->add('heat', ChoiceType::class, [
                'choices' => $this->getChoices()
            ])
            ->add('city')
            ->add('address')
            ->add('postal_code')
            ->add('sold')
            ->add('rooms')
            ->add('options', EntityType::class, [
                'class' => Option::class,
                'required' => false,
                'choice_label' => 'name',
                'multiple' => true,
            ])
            ->add('imageFile', VichImageType::class, [
                'required' => false,
                'label' => 'Image de la propriété',
                'label_attr' => [
                    'class' => 'form-label mt-4'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'forms'
        ]);
    }

    private function getChoices(){
        $choices = Property::HEAT;
        $output = [];
        foreach ($choices as $k => $v){
            $output[$v] = $k;
        }
        return $output;
    }
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use App\Entity\Mail;
use App\Entity\Property;
use App\Entity\PropertySearch;
use App\Form\MailType;
use App\Service\SendMailService;
use Doctrine\Persistence\ManagerRegistry;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Form\PropertySearchType;

class PropertyController extends AbstractController {

    private $repository;

    public function __construct(ManagerRegistry $doctrine)
    {
        $this->repository = $doctrine->getRepository(Property::class);
    }

    /**
     * @param ManagerRegistry $doctrine
     * @return Response
     */
    #[Route('/biens', name: 'property.index')]
    public function index(ManagerRegistry $doctrine, PaginatorInterface $paginator, Request $request): Response
    {

        $propertySearch = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class, $propertySearch);

        $form->handleRequest($request);

        $properties = $paginator->paginate(
            $this->repository->findAllVisibleQuery($propertySearch),
            $request->query->getInt('page', 1),
            12
        );

        /**
         * Récupère les propriétés et change sold à true en base de données
         */
        /*
        $entityManager = $doctrine->getManager();
        $property = $doctrine->getRepository(Property::class)->findAllVisible();
        $property[0]->setSold(true);
        $entityManager->flush();
        dump($property);
        */
        /**
         * Retourne un repo
         */
        /*
        $property = $doctrine->getRepository(Property::class);
        dump($property);
        if (!$property) {
            throw $this->createNotFoundException(
                'No product found for id '
            );
        }*/

        /**
         * Enrichir la db property
         */
        /*
        $entityManager = $doctrine->getManager();
        $property = new Property();
        $property
            ->setTitle('Mon premier bien')
            ->setPrice(200000)
            ->setRooms(4)
            ->setBedrooms(3)
            ->setDescription('Mon petit super appartement')
            ->setSurface(60)
            ->setFloor(4)
            ->setHeat(1)
            ->setCity('Lausanne')
            ->setAddress('Route de Cossonay 108')
            ->setPostalCode(1009);
        $entityManager->persist($property);
        $entityManager->flush();
        */

        return $this->render('property/index.html.twig', [
            'current_menu' => 'active_page',
            'properties' => $properties,
            'form' => $form->createView()
        ]);
    }

    /**
     * @param ManagerRegistry $doctrine
     * @param Property $property
     * @return Response
     */
    #[Route('/biens/{slug}-{id}', name: 'property.show', requirements: ["slug" => "[a-z0-9\-]*"])]
    public function show(Property $property, string $slug, Request $request, SendMailService $sendMailService): Response
    {
        if($property->getSlug() !== $slug){
            return $this->redirectToRoute('property.show', [
                'id' => $property->getId(),
                'slug' => $property->getSlug()
            ], 301);
        }

        $mail = new Mail();
        $mail->setProperty($property);
        $form = $this->createForm(MailType::class, $mail);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $mailIsSend = $sendMailService->notify($mail);
            if($mailIsSend){
                $this->addFlash('success', 'Votre email a bien été envoyé');
            }else{
                $this->addFlash('error', 'Une erreur est survenue');
            }

            return $this->redirectToRoute('property.show', [
                'id' => $property->getId(),
                'slug' => $property->getSlug()
            ]);

        }

        return $this->render('property/show.html.twig', [
            'property' => $property,
            'current_menu' => 'active_page',
            'form' => $form->CreateView()
        ]);
    }


}

templates/property/_property.html.twig
<div class="card mb-4" style="width: 18rem;">
    {% if property.imageName %}
    <img class="card-img-top" src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('miniatures') }}" alt="{{ property.title }}">
    {% else %}
        <img class="card-img-top" src="{{ '/images/property_images/default-miniature.jpg' | imagine_filter('miniatures')}}" alt="{{ property.title }}">
    {% endif %}
    <div class="card-body">
        <a href="{{ path('property.show', {id: property.id, slug: property.slug}) }}"><h5 class="card-title">{{ property.title }}</h5></a>
        <p class="card-text">{{ property.city }} ({{ property.postalCode }})</p>
        <div class="text-primary" style="font-weight: bold; font-size: 2rem;">{{ property.formatedPrice}}</div>
    </div>
</div>

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'Les propriétés' %}

{% block body %}

    <div class="container mt-4">
        <nav class="navbar bg-dark">
            <div class="col align-self-center mt-4 mb-4">
                <form class="" role="search">
                    <div class="row">
                        {{ form_start(form) }}
                        <div class="col-md-3 offset-md-3">
                            {{ form_row(form.minSurface) }}
                        </div>
                        <div class="col-md-3">
                            {{ form_row(form.maxPrice) }}
                        </div>
                        <div class="col-md-3">
                            {{ form_row(form.options) }}
                        </div>
                        <div class="col-md-3">
                            <button class="btn btn-outline-success" type="submit">Rechercher
                            </button>
                        </div>
                        {{ form_end(form) }}
                    </div>
                </form>
            </div>
        </nav>
        <h1 class="mt-4 mb-4 text-center">Voir tous les biens</h1>
        <div class="row">
            {% for property in properties %}
                <div class="col-4">
                    {% include('property/_property.html.twig') %}
                </div>
            {% endfor %}
                <ul class="pagination justify-content-center">
                    {{ knp_pagination_render(properties) }}
                </ul>
            </nav>
        </div>
    </div>

{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}
{% block title property.title %}
{% block body %}
    <div class="container py-4">
        <div class="p-5 mb-4 bg-light rounded-3">
            <div class="container-fluid py-5">
                <div class="row">
                    <div class="col-8">
                        {% if property.imageName %}
                            <img class="card-img-top" src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('medium') }}" alt="{{ property.title }}">
                        {% else %}
                            <img class="card-img-top" src="{{ '/images/property_images/default-medium.jpg' | imagine_filter('medium')}}" alt="{{ property.title }}">
                        {% endif %}
                    </div>
                    <div class="col-4">
                        <h1>{{ property.title }}</h1>
                        <h2>{{ property.rooms }} pièces - {{ property.surface }} m2</h2>
                        <div class="ext-primary" style="font-size: 3rem; font-weight: bold">{{ property.formatedPrice }} CHF</div>
                        <a href="#" class="btn btn-primary">Contacter l'agence</a>
                        <div id="contactForm" class="mt-4">
                            {{ form_start(form) }}
                            <div class="row">
                                <div class="col">{{ form_row(form.firstname) }}</div>
                                <div class="col">{{ form_row(form.lastname) }}</div>
                            </div>
                            <div class="row">
                                <div class="col">{{ form_row(form.phone) }}</div>
                                <div class="col">{{ form_row(form.email) }}</div>
                            </div>
                            {{ form_rest(form) }}
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">Envoyer</button>
                            </div>
                            {{ form_end(form) }}
                        </div>
                    </div>
                </div>
                <p>{{ property.description | nl2br }}</p>
            </div>
        </div>
    </div>
    <div class="container-md mt-40">
        <div class="row">
            <div class="col-8">
                <h2>Caractéristiques</h2>
                <table class="table table-striped">
                    <tr>
                        <td>Surface habitable</td>
                        <td>{{ property.surface }} m2</td>
                    </tr>
                    <tr>
                        <td>Pièces</td>
                        <td>{{ property. rooms }}</td>
                    </tr>
                    <tr>
                        <td>Chambres</td>
                        <td>{{ property.bedrooms }}</td>
                    </tr>
                    <tr>
                        <td>Étage</td>
                        <td>{{ property.floor }}</td>
                    </tr>
                    <tr>
                        <td>Chauffage</td>
                        <td>{{ property.heatType }}</td>
                    </tr>
                </table>
            </div>
            <div class="col-4">
                <h2>Spécificités</h2>
                <ul class="list-group">
                    {% for option in property.options %}
                        <li class="list-group-item">{{ option.name }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}